// machine generated by lolremez and generate.sh

Range ranges[] = {

/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 2, 8 ]
 * with a polynomial of degree 5. */
{ 5, 2, 8, {-4.2130965e-5f,1.3969893e-3f,-2.0713177e-2f,2.2958551e-1f,9.7065859e-1f,-1.9524509e-1f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 8, 16 ]
 * with a polynomial of degree 5. */
{ 5, 8, 16, {-1.331341e-6f,1.0872015e-4f,-4.0853916e-3f,1.1853261e-1f,1.3592346f,-7.699444e-1f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 16, 32 ]
 * with a polynomial of degree 4. */
{ 4, 16, 32, {4.585845e-6f,-6.9556025e-4f,6.0931082e-2f,1.8697867f,-2.6492075f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 32, 64 ]
 * with a polynomial of degree 4. */
{ 4, 32, 64, {7.2222532e-7f,-2.1908775e-4f,3.8384176e-2f,2.3557836f,-6.6755845f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 64, 128 ]
 * with a polynomial of degree 4. */
{ 4, 64, 128, {1.1374336e-7f,-6.9008317e-5f,2.4180516e-2f,2.9681013f,-1.6821419e+1f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 128, 192 ]
 * with a polynomial of degree 4. */
{ 4, 128, 192, {2.7909718e-8f,-2.8452911e-5f,1.6910207e-2f,3.5551218f,-3.485493e+1f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 192, 256 ]
 * with a polynomial of degree 4. */
{ 4, 192, 256, {1.1249317e-8f,-1.6090734e-5f,1.3451214e-2f,3.9877981f,-5.5274065e+1f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 256, 512 ]
 * with a polynomial of degree 4. */
{ 4, 256, 512, {2.8211927e-9f,-6.8464922e-6f,9.5960441e-3f,4.7115671f,-1.0680935e+2f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 512, 1024 ]
 * with a polynomial of degree 3. */
{ 3, 512, 1024, {-7.9677868e-7f,4.5138236e-3f,6.687599f,-4.0461889e+2f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 1024, 2048 ]
 * with a polynomial of degree 3. */
{ 3, 1024, 2048, {-2.5096956e-7f,2.8435307e-3f,8.4258468f,-1.0195757e+3f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 2048, 3072 ]
 * with a polynomial of degree 3. */
{ 3, 2048, 3072, {-1.0448217e-7f,1.9943596e-3f,1.0082948e+1f,-2.1095026e+3f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 3072, 4096 ]
 * with a polynomial of degree 3. */
{ 3, 3072, 4096, {-5.9238277e-8f,1.587609e-3f,1.1307411e+1f,-3.3440485e+3f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 4096, 6144 ]
 * with a polynomial of degree 3. */
{ 3, 4096, 6144, {-3.2909821e-8f,1.2563678e-3f,1.2703719e+1f,-5.3156135e+3f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 6144, 7168 ]
 * with a polynomial of degree 3. */
{ 3, 6144, 7168, {-2.1009273e-8f,1.0478853e-3f,1.3923737e+1f,-7.701167e+3f,}},
/* Approximation of f(x) = pow(x,4/3)
 * on interval [ 7168, 8207 ]
 * with a polynomial of degree 3. */
{ 3, 7168, 8207, {-1.6516898e-8f,9.5167361e-4f,1.4611173e+1f,-9.3398367e+3f,}},
};



